### ISSUE TITLE
Does not work with latest serverless-offline - v6.1.4

### ISSUE THREAD

**Issue by cdelgadob** [ajmath/serverless-offline-scheduler#48]
When updating dependencies to serverless-offline 6.1.4, it doesn't start, the error message is:
```
Type Error ---------------------------------------------

  TypeError: Cannot read property 'location' of undefined
      at Scheduler.run (/Users/carlos/Cheftonic-tech/analytics-backend/node_modules/serverless-offline-scheduler/lib/scheduler.js:63:45)
      at Object.before:offline:start:init [as hook] (/Users/carlos/Cheftonic-tech/analytics-backend/node_modules/serverless-offline-scheduler/index.js:26:61)
      at /Users/carlos/.nvm/versions/node/v12.13.1/lib/node_modules/serverless/lib/classes/PluginManager.js:490:55
      at tryCatcher (/Users/carlos/.nvm/versions/node/v12.13.1/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Object.gotValue (/Users/carlos/.nvm/versions/node/v12.13.1/lib/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:168:18)
      at Object.gotAccum (/Users/carlos/.nvm/versions/node/v12.13.1/lib/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:155:25)
      at Object.tryCatcher (/Users/carlos/.nvm/versions/node/v12.13.1/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/carlos/.nvm/versions/node/v12.13.1/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/Users/carlos/.nvm/versions/node/v12.13.1/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/Users/carlos/.nvm/versions/node/v12.13.1/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/Users/carlos/.nvm/versions/node/v12.13.1/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/Users/carlos/.nvm/versions/node/v12.13.1/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/Users/carlos/.nvm/versions/node/v12.13.1/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/Users/carlos/.nvm/versions/node/v12.13.1/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/Users/carlos/.nvm/versions/node/v12.13.1/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:130:23)
```

**Comment by ecentinela** [comment]
@cdelgadob if it helps, this is the code I have changed to make it work https://github.com/ajmath/serverless-offline-scheduler/pull/49
